version: '3.8'

services:
  fhir-test-runner:
    image: fhir-test-runner:latest
    volumes:
      - ./samples/Test_Scripts:/data/Test_Scripts
      - ./samples/Example_Instances:/data/Example_Instances
      - ./samples/Profiles:/data/Profiles
      - ./impl/config.json:/data/config/config.json
      - ./Results:/data/Results
    environment:
      - PYTHONUNBUFFERED=1
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    network_mode: host
